import _log	 				from "./Log.js";






// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// MARK: Search As You Type
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export default class SearchAsYouType {

	// ────────────────────────────────────
	constructor(args) {
		this.element = null;

		
		// --- Handle new options and source copying ---
		this.allowEditing = args.allowEditing && typeof args.source !== 'function';


		
		// If source is a static array, make a defensive copy to allow mutation
		if (args.source && Array.isArray(args.source.values)) {
			this.source = {
				values: [...args.source.values],
				titles: [...(args.source.titles || args.source.values)]
			};
		} else {
			this.source = args.source; // It's a function, leave it as is
		}


		this.multiple = args.multiple || false;
		this.allowAddItems = args.allowAddItems || false; // New option
		this.name = args.name || 'sayt-' + Math.random().toString(36).substr(2, 4);
		this.var = args.var || args.name;
		this.label = args.label || '';
		this.placeholder = args.placeholder || 'Start typing to search...';
		this.onChange = args.onChange || (() => {});
		this.onChangeSource = args.onChangeSource || (() => {});
		this.minLength = args.minLength || 1;
		this.debounce = args.debounce || 300;

		// Normalize initial value
		if (this.multiple) {
			this.value = Array.isArray(args.value) ? args.value : (args.value ? [args.value] : []);
			this.titles = Array.isArray(args.titles) ? args.titles : (args.titles ? [args.titles] : []);
		} else {
			this.value = args.value || null;
			this.title = args.title || '';
		}

		this.debounceTimer = null;
		this.create();
	}

	// ... (create() method remains the same) ...
	create() {
		this.element = document.createElement('div');
		this.element.className = `aai-group aai-sayt-${this.name}`;


		
		// --- NEW: HTML for the settings button and the editor modal ---
		const settingsButtonHTML = this.allowEditing ? `
			<button type="button" class="aai-sayt-settings-btn" title="Edit items">
				<svg viewBox="0 0 24 24" fill="currentColor"><path d="M19.43 12.98c.04-.32.07-.64.07-.98s-.03-.66-.07-.98l2.11-1.65c.19-.15.24-.42.12-.64l-2-3.46c-.12-.22-.39-.3-.61-.22l-2.49 1c-.52-.4-1.08-.73-1.69-.98l-.38-2.65C14.46 2.18 14.25 2 14 2h-4c-.25 0-.46.18-.49.42l-.38 2.65c-.61.25-1.17.59-1.69.98l-2.49-1c-.23-.09-.49 0-.61.22l-2 3.46c-.13.22-.07.49.12.64l2.11 1.65c-.04.32-.07.65-.07.98s.03.66.07.98l-2.11 1.65c-.19.15-.24.42-.12.64l2 3.46c.12.22.39.3.61.22l2.49-1c.52.4 1.08.73 1.69.98l.38 2.65c.03.24.24.42.49.42h4c.25 0 .46-.18.49-.42l.38-2.65c.61-.25 1.17-.59 1.69-.98l2.49 1c.23.09.49 0 .61-.22l2-3.46c.12-.22.07-.49-.12-.64l-2.11-1.65zM12 15.5c-1.93 0-3.5-1.57-3.5-3.5s1.57-3.5 3.5-3.5 3.5 1.57 3.5 3.5-1.57 3.5-3.5 3.5z"/></svg>
			</button>
		` : '';

		const editorModalHTML = this.allowEditing ? `
			<div class="aai-sayt-editor-overlay" style="display: none;">
				<div class="aai-sayt-editor-modal">
					<div class="aai-sayt-editor-header">
						<h3>Edit Items</h3>
						<button type="button" class="aai-sayt-editor-close-btn" title="Close">×</button>
					</div>
					<div class="aai-sayt-editor-content">
						<table class="aai-sayt-editor-table">
							<thead>
								<tr>
									<th>Value</th>
									<th>Title</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								<!-- Rows will be generated by JS -->
							</tbody>
						</table>
					</div>
					<div class="aai-sayt-editor-footer">
						<button type="button" class="aai-sayt-editor-cancel-btn">Cancel</button>
						<button type="button" class="aai-sayt-editor-save-btn">Save Changes</button>
					</div>
				</div>
			</div>
		` : '';



		const HTML = `
            ${this.label ? `<label class="aai-label" for="sayt-input-${this.name}">${this.label}</label>` : ''}
            <div class="aai-sayt-container">
                <div class="aai-sayt-input-wrapper">
                    <input 
                        type="text" 
                        id="sayt-input-${this.name}" 
                        class="aai-sayt-input" 
                        placeholder="${this.placeholder}" 
                        autocomplete="off"
                    >
                    <div class="aai-sayt-loader"></div>
					${settingsButtonHTML}
                </div>
                <div class="aai-sayt-dropdown">
                    <div class="aai-sayt-options"></div>
                    <div class="aai-sayt-no-results" style="display: none;">No results found</div>
                </div>
            </div>
            ${this.multiple ? '<div class="aai-sayt-chips"></div>' : ''}
            <input hidden id="${this.var}" name="${this.var}" type="text">
			${editorModalHTML}
        `;

		this.element.innerHTML = HTML;
		this.html = `<div class="aai-group aai-sayt-${this.name}">${HTML}</div>`;

		requestAnimationFrame(() => {
			this.events();
		});
	}


	// ────────────────────────────────────
	// MARK: Event Handling
	// ────────────────────────────────────
	events() {
		const group = document.querySelector(`.aai-sayt-${this.name}`);
		if (!group) return;

		const input = group.querySelector('.aai-sayt-input');
		const dropdown = group.querySelector('.aai-sayt-dropdown');
		const optionsContainer = group.querySelector('.aai-sayt-options');
		const loader = group.querySelector('.aai-sayt-loader');
		const noResults = group.querySelector('.aai-sayt-no-results');
		const chipsContainer = group.querySelector('.aai-sayt-chips');
		const hiddenInput = group.querySelector(`#${this.var}`);


		
		// --- NEW: Event listeners for the editor ---
		if (this.allowEditing) {
			const settingsBtn = group.querySelector('.aai-sayt-settings-btn');
			const editorOverlay = group.querySelector('.aai-sayt-editor-overlay');
			const closeModalBtn = group.querySelector('.aai-sayt-editor-close-btn');
			const cancelBtn = group.querySelector('.aai-sayt-editor-cancel-btn');
			const saveBtn = group.querySelector('.aai-sayt-editor-save-btn');

			settingsBtn.addEventListener('click', () => openSourceEditor());
			closeModalBtn.addEventListener('click', () => closeSourceEditor());
			cancelBtn.addEventListener('click', () => closeSourceEditor());
			editorOverlay.addEventListener('click', (e) => {
				if (e.target === editorOverlay) closeSourceEditor();
			});
			saveBtn.addEventListener('click', () => saveSourceChanges());
			
			// Close on escape key
			document.addEventListener('keydown', (e) => {
				if (e.key === 'Escape' && editorOverlay.style.display !== 'none') {
					closeSourceEditor();
				}
			});
		}


		let self = this;
		let tempSource = null; // To hold data while editing in the modal


		function openSourceEditor() {
			const editorOverlay = group.querySelector('.aai-sayt-editor-overlay');
			const tableBody = group.querySelector('.aai-sayt-editor-table tbody');
			
			// Deep copy the source for temporary editing
			tempSource = {
				values: [...self.source.values],
				titles: [...self.source.titles]
			};

			tableBody.innerHTML = tempSource.values.map((value, index) => `
				<tr data-index="${index}">
					<td><input type="text" class="aai-sayt-editor-input" value="${value}"></td>
					<td><input type="text" class="aai-sayt-editor-input" value="${tempSource.titles[index]}"></td>
					<td><button type="button" class="aai-sayt-editor-remove-btn" title="Remove item">×</button></td>
				</tr>
			`).join('');
			
			// Add event listeners for remove buttons
			tableBody.querySelectorAll('.aai-sayt-editor-remove-btn').forEach(btn => {
				btn.addEventListener('click', (e) => {
					e.target.closest('tr').remove();
				});
			});

			editorOverlay.style.display = 'flex';
		}

		function closeSourceEditor() {
			group.querySelector('.aai-sayt-editor-overlay').style.display = 'none';
			tempSource = null; // Clear temporary data
		}

		function saveSourceChanges() {
			const tableBody = group.querySelector('.aai-sayt-editor-table tbody');
			const newValues = [];
			const newTitles = [];

			tableBody.querySelectorAll('tr').forEach(row => {
				const inputs = row.querySelectorAll('input');
				newValues.push(inputs[0].value);
				newTitles.push(inputs[1].value);
			});
			
			// Update the master source
			self.source.values = newValues;
			self.source.titles = newTitles;
			
			// Refresh UI elements that depend on the source
			refreshChips();
			
			// Fire the onChange event with the special action
			self.onChange(self.value, {}, 'source-update', self.source);
			self.onChangeSource( self.source );
			
			closeSourceEditor();
		}

		function refreshChips() {
			if (!self.multiple || !chipsContainer) return;
			
			const existingValues = self.value;
			const newValidValues = [];
			const newValidTitles = [];

			// Clear existing chips
			chipsContainer.innerHTML = '';
			
			// Re-add chips only for values that still exist in the new source
			existingValues.forEach(val => {
				const index = self.source.values.indexOf(val);
				if (index > -1) {
					newValidValues.push(val);
					newValidTitles.push(self.source.titles[index]);
					addChip(val, self.source.titles[index]);
				}
			});
			
			// Update the component's internal value state
			self.value = newValidValues;
			self.titles = newValidTitles;
			updateHiddenInput();
		}






		input.addEventListener('input', () => {
			const query = input.value.trim();
			clearTimeout(this.debounceTimer);
			this.debounceTimer = setTimeout(() => {
				if (query.length >= this.minLength) {
					performSearch(query);
				} else {
					closeDropdown();
				}
			}, this.debounce);
		});

		optionsContainer.addEventListener('click', (e) => {
			const option = e.target.closest('.aai-sayt-option');
			if (option) {
				// Pass the whole dataset to selectOption
				selectOption(option.dataset);
			}
		});



		// ... (keyboard nav and outside click listeners) ...
		input.addEventListener('keydown', handleKeyboardNav);
		optionsContainer.addEventListener('keydown', handleKeyboardNav);


		// Close dropdown when clicking outside
		document.addEventListener('click', (e) => {
			if (!group.contains(e.target)) {
				closeDropdown();
			}
		});



		async function performSearch(query) {
			loader.style.display = 'block';
			noResults.style.display = 'none';
			optionsContainer.innerHTML = '';
			const lowerCaseQuery = query.toLowerCase();

			try {
				let results = [];
				if (typeof self.source === 'function') {
					results = await self.source(query);
				} else if (self.source && Array.isArray(self.source.values)) {
					results = self.source.values.map((value, index) => ({
						value,
						title: self.source.titles[index] || value
					})).filter(item =>
						item.title.toLowerCase().includes(lowerCaseQuery)
					);
				}
				
				// --- NEW: LOGIC FOR "ALLOW ADD ITEMS" ---
				if (self.allowAddItems && typeof self.source !== 'function') {
					const isExactMatch = self.source.titles.some(title => title.toLowerCase() === lowerCaseQuery);
					if (!isExactMatch) {
						// Prepend an "Add" option to the results
						results.unshift({
							value: query,      // The value will be the query itself
							title: `Add "${query}"`,
							isNew: true        // Special flag
						});
					}
				}
				// --- END NEW LOGIC ---

				renderOptions(results, query);
			} catch (error) {
				_log('❌ Search failed:', error);
				noResults.textContent = 'Error fetching results';
				noResults.style.display = 'block';
			} finally {
				loader.style.display = 'none';
			}
		}

		function renderOptions(results, query) {
			if (results.length === 0) {
				noResults.style.display = 'block';
				closeDropdown();
				return;
			}
			
			const optionsHTML = results.map(item => {
				// --- NEW: HANDLE "isNew" flag ---
				const isNewClass = item.isNew ? 'aai-sayt-option-new' : '';
				const isNewAttr = item.isNew ? 'data-is-new="true"' : '';
				const value = item.isNew ? item.value : item.value; // for new items, value is the query
				const title = item.isNew ? item.value : item.title; // for new items, we select the query as title

				return `
					<div class="aai-sayt-option ${isNewClass}" data-value="${value}" data-title="${title}" ${isNewAttr} tabindex="0">
						${item.title}
					</div>
				`;
			}).join('');

			optionsContainer.innerHTML = optionsHTML;
			dropdown.classList.add('show');
		}

		function selectOption(dataset) {
			const { value, title, isNew } = dataset;
			
			
			// --- NEW: Create the `changedItem` object first ---
			const changedItem = {
				value: value,
				title: title,
			};

			
			// --- NEW: Add the isNew flag to the changedItem object ---
			if (isNew) {
				// Add the new item to the internal source arrays
				self.source.values.push(value);
				self.source.titles.push(title); // For new items, title is the same as value
				
				// Mark this specific change as "new"
				changedItem.isNew = true;
			}

			if (self.multiple) {
				if (!self.value.includes(value)) {
					self.value.push(value);
					self.titles.push(title);
					addChip(value, title);
					// Pass the updated source in onChange
					self.onChange(self.value, changedItem, 'add', self.source);
					self.onChangeSource( self.source );
				}
				input.value = '';
				input.focus();
			} else {
				self.value = value;
				self.title = title;
				input.value = title;
				self.onChange(self.value, changedItem, 'select', self.source);
			}
			updateHiddenInput();
			closeDropdown();
		}
		
		function removeChip(valueToRemove) {
			const index = self.value.indexOf(valueToRemove);
			if (index > -1) {
				const removedTitle = self.titles[index];
				self.value.splice(index, 1);
				self.titles.splice(index, 1);

				const chip = chipsContainer.querySelector(`[data-value="${valueToRemove}"]`);
				if (chip) chip.remove();

				updateHiddenInput();
				// Pass the source here too for consistency, even though it's not changed on remove
                const changedItem = { value: valueToRemove, title: removedTitle };
				self.onChange(self.value, changedItem, 'remove', self.source);
			}
		}

		// ... (rest of the functions: addChip, updateHiddenInput, closeDropdown, handleKeyboardNav, initializeUI) ...
		// The only change is in handleKeyboardNav to pass the full dataset
		
		function handleKeyboardNav(e) {
			const visibleOptions = Array.from(optionsContainer.querySelectorAll('.aai-sayt-option'));
			if (!visibleOptions.length) return;

			const focusedElement = document.activeElement;
			
			if (e.key === 'Enter' && focusedElement.classList.contains('aai-sayt-option')) {
				e.preventDefault();
				selectOption(focusedElement.dataset); // Pass full dataset
				return; // Prevent other actions
			}
			
			// ... (ArrowUp, ArrowDown, Escape logic remains the same)
			const currentIndex = visibleOptions.indexOf(focusedElement);
			
			if (e.key === 'ArrowDown') {
				e.preventDefault();
				const nextIndex = (currentIndex + 1) % visibleOptions.length;
				visibleOptions[nextIndex].focus();
			} else if (e.key === 'ArrowUp') {
				e.preventDefault();
				const prevIndex = (currentIndex - 1 + visibleOptions.length) % visibleOptions.length;
				visibleOptions[prevIndex].focus();
			} else if (e.key === 'Escape') {
				closeDropdown();
				input.focus();
			}
		}

		// Other functions (addChip, etc.) are unchanged but are included for completeness
		function addChip(value, title) {
			if (!chipsContainer) return;
			const chip = document.createElement('div');
			chip.className = 'aai-multi-select-chip';
			chip.dataset.value = value;
			chip.innerHTML = `
                <span>${title}</span>
                <button type="button" class="aai-multi-select-chip-remove" data-value="${value}" title="Remove ${title}">×</button>
            `;

			chip.querySelector('.aai-multi-select-chip-remove').addEventListener('click', (e) => {
				removeChip(e.target.dataset.value);
			});

			chipsContainer.appendChild(chip);
		}
		
		function updateHiddenInput() {
			hiddenInput.value = self.multiple ? self.value.join(',') : self.value;
		}

		function closeDropdown() {
			dropdown.classList.remove('show');
		}

		function initializeUI() {
			if (self.multiple) {
				self.value.forEach((val, index) => {
					addChip(val, self.titles[index] || val);
				});
			} else {
				if (self.value && self.title) {
					input.value = self.title;
				}
			}
			updateHiddenInput();
		}
		
		initializeUI();
	}
}






// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// MARK: Example Usage
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/*
// Assuming this code is in a file where SearchAsYouType is imported.
// And you have a container element in your HTML: <div id="my-sayt-container"></div>

const container = document.getElementById('my-sayt-container');

// --------------------------------------
// Example 1: Static Array Source (Multiple Selection)
// --------------------------------------
const arrayMultiSelect = new SearchAsYouType({
    name: 'fruits-multi',
    label: 'Select Your Favorite Fruits (Multiple)',
    multiple: true,
    source: {
        values: ['apple', 'banana', 'orange', 'grape', 'mango', 'strawberry'],
        titles: ['Apple', 'Banana', 'Orange', 'Grape', 'Mango', 'Strawberry']
    },
    // Pre-selected values
    value: ['apple', 'mango'],
    titles: ['Apple', 'Mango'], // Provide titles for pre-selected values
    onChange: (currentValues, changedItem, action) => {
        console.log('Current selection:', currentValues);
        console.log(`Item ${changedItem.title} was ${action}.`);
    }
});
// container.appendChild(arrayMultiSelect.element);


// --------------------------------------
// Example 2: Static Array Source (Single Selection)
// --------------------------------------
const arraySingleSelect = new SearchAsYouType({
    name: 'country-single',
    label: 'Select Your Country (Single)',
    multiple: false,
    source: {
        values: ['us', 'ca', 'mx', 'uk', 'de', 'fr'],
        titles: ['United States', 'Canada', 'Mexico', 'United Kingdom', 'Germany', 'France']
    },
    // Pre-selected value
    value: 'uk',
    title: 'United Kingdom', // Provide the title for the pre-selected value
    onChange: (currentValue, selectedItem) => {
        console.log('Selected country code:', currentValue);
        console.log('You selected:', selectedItem.title);
    }
});
// container.appendChild(arraySingleSelect.element);


// --------------------------------------
// Example 3: Dynamic Function Source (e.g., a Fake API)
// --------------------------------------
// This function simulates an API call that returns a Promise.
const fakeApiSearch = (query) => {
    console.log(`Searching API for: ${query}`);
    return new Promise(resolve => {
        const mockData = [
            { id: 101, name: 'Alice Smith', email: 'alice@example.com' },
            { id: 102, name: 'Bob Johnson', email: 'bob@example.com' },
            { id: 103, name: 'Charlie Brown', email: 'charlie@example.com' },
            { id: 104, name: 'Diana Prince', email: 'diana@example.com' },
        ];
        
        // Simulate network delay
        setTimeout(() => {
            const results = mockData
                .filter(user => user.name.toLowerCase().includes(query.toLowerCase()))
                .map(user => ({ value: user.id, title: `${user.name} (${user.email})` })); // Transform to {value, title} format
            
            resolve(results);
        }, 500); // 500ms delay
    });
};

const apiSelect = new SearchAsYouType({
    name: 'user-search',
    label: 'Search for a User (API)',
    multiple: false,
    placeholder: 'e.g., Alice, Bob...',
    source: fakeApiSearch, // Pass the function directly
    minLength: 2, // Start searching after 2 characters
    onChange: (value, item) => {
        console.log('Selected User ID:', value);
        console.log('Item:', item);
    }
});
// container.appendChild(apiSelect.element);


// --------------------------------------
// Example 4: WordPress Posts Source (using REST API)
// --------------------------------------
// This source function fetches posts from a WordPress REST API.
// It assumes you're on a WP site or have access to a WP REST API endpoint.
const wpPostSource = async (query) => {
    // In a real WP environment, you might use wp.apiFetch
    // const results = await wp.apiFetch({ path: `/wp/v2/posts?search=${query}&_fields=id,title` });
    
    // For a generic example, we use fetch:
    const response = await fetch(`/wp-json/wp/v2/posts?search=${encodeURIComponent(query)}&_fields=id,title&per_page=5`);
    
    if (!response.ok) {
        throw new Error('WordPress API request failed');
    }
    
    const posts = await response.json();
    
    // Transform the API response into the {value, title} format the component expects
    return posts.map(post => ({
        value: post.id,
        title: post.title.rendered // The title is often in a 'rendered' property
    }));
};

const wpPostSelect = new SearchAsYouType({
    name: 'wp-post-selector',
    label: 'Link to a Post',
    multiple: true,
    source: wpPostSource,
    minLength: 3,
    placeholder: 'Search posts by title...',
    onChange: (values) => {
        console.log('Selected Post IDs:', values);
    }
});
// container.appendChild(wpPostSelect.element);




/*
// --------------------------------------
// Example 5: Dynamic Tag Input (AllowAddItems)
// --------------------------------------

const tagInput = new SearchAsYouType({
    name: 'tags',
    label: 'Add Tags',
    multiple: true,
    allowAddItems: true, // Enable the new feature
    source: {
        values: ['javascript', 'react', 'css', 'html', 'nodejs'],
        titles: ['JavaScript', 'React', 'CSS', 'HTML', 'Node.js']
    },
    value: ['react'], // Pre-selected
    titles: ['React'],
    placeholder: 'Search for existing tags or add new ones...',
    onChange: (currentValues, changedItem, action, updatedSource) => {
        console.log('Current tags:', currentValues);
        console.log(`Item "${changedItem.title}" was ${action}.`);
        
        if (action === 'add' && changedItem.isNew) {
            console.log('A new tag was created!');
        }

        // You now have the full, updated source list
        console.log('Updated source list:', updatedSource.titles);

        // You could now, for example, save this updatedSource to your database
        // saveTagsToDatabase(updatedSource);
    }
});

// Assuming 'container' is your DOM element
// container.appendChild(tagInput.element);



// --------------------------------------
// Example 6: Editor enabled
// --------------------------------------
const editableSelect = new SearchAsYouType({
    name: 'categories',
    label: 'Select Categories',
    multiple: true,
    allowEditing: true, // Enable the editor modal
    source: {
        values: ['tech', 'health', 'finance', 'lifestyle'],
        titles: ['Technology', 'Health & Wellness', 'Finance', 'Lifestyle']
    },
    value: ['tech', 'finance'],
    onChange: (currentValue, changedItem, action, updatedSource) => {
        console.log(`Action: ${action}`);
        console.log('Current selection:', currentValue);

        if (action === 'source-update') {
            console.log('The entire source list was updated!');
            console.log('New source:', updatedSource);
            // Here you would make an API call to save the new list of categories
            // saveCategoriesToDatabase(updatedSource);
        } else {
            console.log('Changed Item:', changedItem);
        }
    }
});






// --------------------------------------
// Another possible source: WooCommerce Products
// You would create a function similar to wpPostSource, but hit the /wc/v3/products endpoint.
// The principle remains the same: the function takes a query and returns a Promise
// that resolves to an array of {value, title} objects.
// --------------------------------------

*/


